### ISSUE TITLE
Decoding data

### ISSUE THREAD

**Issue by MichaelBaker** [confluentinc/bottledwater-pg#13]
I'm trying to use your output decoder by itself. When I run the output it produces through `avro-tools fragtojson inline-schema` or `avro-tools tojson`, I get a parse error. Do I need to do something special to view the data of the output decoder or is your format only usable with the client you've written?

**Comment by ept** [comment]
What's your use case? If you want to get data out of Postgres, but not ship it to Kafka, I suggest you use the Bottled Water client anyway. `client/bwtest.c` is an example of a program that just prints to stdout rather than sending to Kafka.

Consuming the Avro-encoded data yourself isn't really an intended use case right now, so it's not particularly documented. You're best off reading the source, but here's a high-level summary:

To decode Avro, you need the schema with which it was written. Bottled Water embeds that schema in both the plugin and the client (see `ext/protocol.{c,h}`). You can also query the schema from SQL: `select bottledwater_frame_schema();`

That schema is for the data frames. Each frame represents one or more events, which are beginning or committing a transaction, inserting/updating/deleting a row, or registering a new data schema. The data schemas are what is used to encode the actual row-level data, i.e. there are two levels of Avro schema: frames and data.

Note that if you're using `pg_recvlogical` as a client, it inserts gratuitous newline characters which you'll have to strip out.

Hope that helps!
