### ISSUE TITLE
Standalone Avro encoder

### ISSUE THREAD

**Issue by nightscape** [confluentinc/bottledwater-pg#22]
Hi!
I'm wondering if it would be possible to extract the Avro encoding part as a standalone extension that provides functions to encode schemas and tuples.
In our case, we want to stream data directly from Postgres (behind a thin Ruby service) to a client.
Converting to Avro in the Ruby service costs a lot of performance, so having a possibility to make PG return Avro directly would be great and as I see it bottledwater-pg should already have the required code.

What do you think?

Best
  Martin

**Comment by ept** [comment]
Do I understand correctly that you just want a dump of the database contents as Avro, but you don't need the ongoing stream of writes? You can use the `bottledwater_export()` function that is [created by the extension](https://github.com/confluentinc/bottledwater-pg/blob/master/ext/bottledwater--0.1.sql#L13). You can give it a pattern of table names and it will return all the rows in the table in Avro format.

**Comment by nightscape** [comment]
Hi @ept,

sorry for taking so long to respond, Avro fell a little under the table due to more important stuff...
the ```bottledwater_export()``` is almost what we'd need, except that we would like to fire arbitrary queries. We could probably work around this using temp tables, but that would delay the start of streaming and potentially create a lot of IO if results are big.

**Comment by ept** [comment]
Sorry for the delay. I think this would be possible in principle, by having a function that operates on one tuple at a time. However, I think that for Bottled Water's purposes it is better if `bottledwater_export()` generates its own queries, rather than letting the client send arbitrary queries, because it allows BW to do stuff like take a shared lock on all the tables (to prevent concurrent DDL while the snapshot is happening).

If you want to try separating out to the Avro encoding into a separate project, you're welcome to use the BW code as a starting point. If Avro encoding was a separate library, BW could potentially switch to using it, but I don't see that as a priority right now. For now, I'll close this issue until we have a clearer idea of how this might work.
