### ISSUE TITLE
Updating Postgres Table Schema Kills ./kafka/bottledwater

### ISSUE THREAD

**Issue by tjgillies** [confluentinc/bottledwater-pg#23]
When I update my Postgres table schema and then add a row, the ./kafka/bottledwater process dies and says:

> Response from schema registry is too large
./kafka/bottledwater: Could not send schema to registry: Failed writing body (0 != 5575)

**Comment by ept** [comment]
Bottled Water currently assumes that the schema registry's response is less than 1kB. Seems like that's not the case here. You can adjust the limit in [registry.c:143](https://github.com/confluentinc/bottledwater-pg/blob/8a11825/kafka/registry.c#L143) — perhaps bump it up to 10kB and see if it works. Also, would you mind pasting the schema registry's response here? I'd like to understand what causes such a long response, to determine what the limit should be.

**Comment by th3jamin** [comment]
I have run into a similar issue. If I add a single text column to my schema and attempt and insert I receive the same error. Now for testing I increased the buffer to 1MB, this removes the "too large" error message above. However it still errors out with the following response from the schema-registry:

./kafka/bottledwater: Schema registry returned HTTP status 409: Schema being registered is incompatible with the latest schema io.confluent.kafka.schemaregistry.rest.exceptions.RestIncompatibleAvroSchemaException: Schema being registered is incompatible with the latest schema
io.confluent.kafka.schemaregistry.rest.exceptions.RestIncompatibleAvroSchemaException: Schema being registered is incompatible with the latest schema
	at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.incompatibleSchemaException(Errors.java:62)

**Comment by ept** [comment]
@th3jamin Could you please log the response from the schema registry? I'm curious to see why it is so long.

For the incompatible schema error, you need to disable compatibility checking for now:

```
$ curl -X PUT -i -H "Content-Type: application/vnd.schemaregistry.v1+json" \
    --data '{"compatibility": "NONE"}' \
    http://localhost:8081/config
```

I want to change Bottled Water so that it meets the compatibility check (so that you don't need to disable it), but I've not had a chance yet. This is tracked in issue #1.

**Comment by th3jamin** [comment]
@ept I have the schema-registry set to debug=true but nothing of use is printed except the 409 error code. Is there an alternative way to turn on more verbose logging on the schema-registry?

**Comment by ept** [comment]
@th3jamin You could log it in the Bottled Water client, e.g. by adding something like this to `registry_parse_response()` in [registry.c](https://github.com/confluentinc/bottledwater-pg/blob/master/kafka/registry.c#L193):

```c
if (resp_len >= 1024) {
    fprintf(stderr, "%.*s\n", resp_len, resp_body);
}
```

**Comment by th3jamin** [comment]
@ept 
Unfortunately your debugging idea won't work as the curl command has not finished parsing the response before it errors out so that callback will never be called. Anyway I added some debugging to print the request to the schema-registry and ran curl on my own, the response is below. The reason it is so long is because it is an error message. Ideally registry.c should handle errors a bit more gracefully as the error message is totally lost in the current code. This is obviously issue #1.

{
    "error_code": 409,
    "message": "Schema being registered is incompatible with the latest schema io.confluent.kafka.schemaregistry.rest.exceptions.RestIncompatibleAvroSchemaException: Schema being registered is incompatible with the latest schema
io.confluent.kafka.schemaregistry.rest.exceptions.RestIncompatibleAvroSchemaException: Schema being registered is incompatible with the latest schema
\tat io.confluent.kafka.schemaregistry.rest.exceptions.Errors.incompatibleSchemaException(Errors.java:62)
\tat io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.register(SubjectVersionsResource.java:166)
\tat sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
\tat java.lang.reflect.Method.invoke(Method.java:497)
\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136)
\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:406)
\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:350)
\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
\tat org.glassfish.jersey.internal.Errors.process(Errors.java:315)
\tat org.glassfish.jersey.internal.Errors.process(Errors.java:297)
\tat org.glassfish.jersey.internal.Errors.process(Errors.java:267)
\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:319)
\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:219)
\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
\tat org.eclipse.jetty.server.Server.handle(Server.java:370)
\tat org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
\tat org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
\tat org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
\tat org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
\tat org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
\tat org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
\tat org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
\tat java.lang.Thread.run(Thread.java:745)
Caused by: io.confluent.kafka.schemaregistry.exceptions.IncompatibleSchemaException: New schema is incompatible with the latest schema {subject=test-key,version=1,id=21,schema={\"type\":\"record\",\"name\":\"test_pkey\",\"namespace\":\"com.martinkl.bottledwater.dbschema.public\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"int\"]}]}}
\tat io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.register(KafkaSchemaRegistry.java:316)
\tat io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.registerOrForward(KafkaSchemaRegistry.java:338)
\tat io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.register(SubjectVersionsResource.java:154)
\t... 46 more
"
}

**Comment by ept** [comment]
I've swapped out the fixed-size buffer for a growable buffer, so an unexpectedly large response from the schema registry should no longer cause things to blow up.
