### ISSUE TITLE
Handle checkpoints in the absence of database activity

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [confluentinc/bottledwater-pg#68]
It seems that in the absence of database activity, where only timeout-driven checkpoints are occurring,  bottledwater is not well-behaved as a logical replication stream consumer and can cause its `restart_lsn` (according to [`pg_stat_replication_slots`](http://www.postgresql.org/docs/9.4/static/catalog-pg-replication-slots.html)) to remain static, most likely causing the server's disk to fill up.

/cc @samstokes

**Comment by samstokes** [comment]
From chat:

> See http://www.postgresql.org/docs/current/static/app-pgrecvlogical.html
> "The server will occasionally request the client to perform a flush and report the flush position to the server. This setting is in addition to that, to perform flushes more frequently."
> The streaming replica is obligated to report a flushed-up-to point using replication protocol messages.
> (In addition to wrote-up-to messages)

I think the problem is that BW does so, but only after successfully sending a message to Kafka, but obviously a checkpoint wouldn't result in sending a message.

@ept does this ring any bells?  I should have bandwidth to work on this soon, but I'm less familiar with the semantics of the replication protocol client, so want to check I know what I'm doing before blundering in.

**Comment by uhoh-itsmaciek** [comment]
This was closed inadvertently.
