### ISSUE TITLE
Replication per table and start offset

### ISSUE THREAD

**Issue by jtuthehien** [confluentinc/bottledwater-pg#74]
Hi everyone. 
I've started looking into bottlewater to ship our data from postgres to elasticsearch and have some queries.
Would it be possible to process on some specific tables, not the whole database ? 
Also, how do I define the offset (xlog) which it start to send replication event, let's say I dont want it to start streaming from beginning of time, but maybe those changes starting from beginning of this year ( 1 Jan 2016) onward ?

**Comment by ept** [comment]
@jtuthehien Thanks for trying Bottled Water.

> Would it be possible to process on some specific tables, not the whole database ? 

See #21. Postgres itself always replicates an entire database at a time, but we are planning to add a feature to Bottled Water to allow selecting certain tables.

> Also, how do I define the offset (xlog) which it start to send replication event, let's say I dont want it to start streaming from beginning of time, but maybe those changes starting from beginning of this year ( 1 Jan 2016) onward ?

I believe that isn't possible, because Postgres garbage-collects the transaction log fairly frequently; unless you have specifically configured it to have a long retention period, the transaction logs from a few months ago will long since be gone. That's why Bottled Water takes a consistent snapshot of the database, and coordinates the snapshot with the start of the transaction log decoding, which will then capture changes from that point forward.
