### ISSUE TITLE
Replication slot

### ISSUE THREAD

**Issue by uyjco0** [confluentinc/bottledwater-pg#76]
Two questions about replication slots:

- In the README we have the following statement "When you no longer want to run Bottled Water, you have to drop its replication slot ". I can see that the file "_./client/replication.c_" has the function "_replication_slot_drop_". Is it possible that the bottledwater client is applying this function automatically before it is going down?

- When using a sharded database, as for example [Citus](https://www.citusdata.com), do we need to add the IP of the  bottledwater client in the "_pg_hba.conf_" of each Worker and Master (i.e. logical master)?   Or it is enough with doing that only for the Master 's "_pg_hba.conf_"? Which Pg string connection we are giving to the bottledwater client (Master?)? Is there needed some other additional step in order to configure the  bottledwater client (and Logical Decoding) with this kind of database?

Thanks!

**Comment by ept** [comment]
@uyjco0 

> I can see that the file "./client/replication.c" has the function "replication_slot_drop". Is it possible that the bottledwater client is applying this function automatically before it is going down?

Bottled Water only tries to automatically drop the replication slot if the database snapshot fails. If the snapshot successfully completes and it switches over to logical replication mode, the replication slot remains in place forever until you manually delete it.

The reason for that behaviour is as follows: Bottled Water uses the presence of the replication slot in order to determine whether to take a snapshot; a snapshot is only taken if the replication slot does not exist — in other words, the first time you start Bottled Water. This has the nice property that if the streaming replication client crashes, you can simply restart it, and it will continue where it left off (without missing writes, and without taking another snapshot).

You can see more on managing replication slots [in the Postgres docs](http://www.postgresql.org/docs/current/static/logicaldecoding-example.html).

> When using a sharded database, as for example Citus, do we need to add the IP of the bottledwater client in the "pg_hba.conf" of each Worker and Master (i.e. logical master)?

I'm afraid I've never used Citus, so I have no idea. It would be great if you could give it a try and let us know. Thanks!

**Comment by uyjco0** [comment]
Hi Martin,

Regards the Replication Slot, yes, there are more advantages with the current setting.

I'll try with Citus and send my feedback to you.

Thanks a lot!
