### ISSUE TITLE
Bottledwater-pg client scalability

### ISSUE THREAD

**Issue by uyjco0** [confluentinc/bottledwater-pg#80]
Hi,

I was doing a little demo of a distributed app using the bottledwater-pg plugin/client (check at uyjco0/node-scalable), and I have the following question: is it possible to make the bottledwater-pg client to use all/some of the available cores in the host?

Thanks!

**Comment by ept** [comment]
Hi @uyjco0, at the moment the client is unfortunately only single-threaded (apart from the Kafka client, which I believe already uses multiple threads internally and can thus use multiple cores).

It would not be straightforward to spread the load over multiple cores, because Bottled Water has to receive data from the Postgres server over a single network connection, and it has to maintain ordering of updates (when processing updates to the same row, it's important to know which happened later). It might be possible to put some of the deserialization work onto a thread pool, but it would take some care to get right.

The best way of scaling the system would probably be to shard Postgres itself, and then you can have a separate client per shard. But of course that would mean all clients have to be aware of the sharding.

**Comment by uyjco0** [comment]
Thanks @ept!

Yes, in fact sharding is an option, for this reason I was opening #76 , where I was asking how to configure the Bottledwater-pg client with Citus (a sharding solution for PostgreSQL).

**Comment by ept** [comment]
Ah, got it now — I didn't make the link :)

**Comment by uyjco0** [comment]
I still didn't test PostgreSQL + Citus + Bottledwater-pg, the current demo is using a Master/Slave configuration, that for a lot of contexts is enough ..
