### ISSUE TITLE
Does bottledwater need SELECT privilege?

### ISSUE THREAD

**Issue by abcfy2** [confluentinc/bottledwater-pg#82]
I find this error:

```
# bottledwater -d postgres://repl:password@127.0.0.1/mybw -b 172.16.250.10:9092 -f json
Writing messages to Kafka in JSON format
Created replication slot "bottledwater", capturing consistent snapshot "0049D4AD-1".
INFO:  bottledwater_export: Table public.test is keyed by index test_pkey
INFO:  bottledwater_export: Table public.moni_inbox is keyed by index moni_inbox_PK
bottledwater: While reading snapshot: PGRES_FATAL_ERROR: ERROR:  permission denied for relation test

Dropping replication slot since the snapshot did not complete successfully.
```

The role `repl` has the `REPLICATION` privilege. After grant SELECT privilege to `repl`, it works.

```sql
GRANT SELECT ON test TO repl;
GRANT SELECT ON moni_inbox TO repl;
```

But sometime it seems that it's no need to grant SELECT privilege. README doc does not mention this. Does bottledwater need SELECT privilege?

**Comment by samstokes** [comment]
Hi, I haven't tested exactly which privileges are needed, but I would expect the SELECT privilege to be need as well, as the initial snapshot does a `SELECT *` to capture the existing table contents.

The README doesn't currently document the full set of privileges needed, since I think it's assuming a default setup where the user account is the one that created the tables and already has privileges on those tables.  If you do discover the exact privileges needed, we'd welcome a pull request to add it to the README!
