### ISSUE TITLE
Does bottled water work with existing cluster?

### ISSUE THREAD

**Issue by asr1901** [confluentinc/bottledwater-pg#89]
We are already using repmgr to have two standbys for our primary database.  We would like to use bottledwater-pg to stream changes to an analytics platform, however, because our wal-level is already set to "hot standby" for the repmgr cluster to work, does that mean we will be unable to use bottledwater?  Is it possible to use bottledwater with a downstream machine ?

**Comment by ept** [comment]
@asr1901 You should still be able to use Bottled Water. You'll need to increase the wal-level to "logical"; [according to the Postgres docs](https://www.postgresql.org/docs/current/static/runtime-config-wal.html), the "logical" level contains all the information that the "hot_standby" level contains, so your standby setup should continue to work.

Unfortunately the Bottled Water plugin has to be installed on the primary database; the Postgres logical decoding feature is currently not supported on standbys (this is a limitation of Postgres, not of Bottled Water).

**Comment by samstokes** [comment]
> the Postgres logical decoding feature is currently not supported on standbys

Since I happen to have this bookmarked, here's a [mailing list thread](https://www.postgresql.org/message-id/1453217433.421060638@f409.i.mail.ru) where this limitation was discussed.  That's the most recent discussion I've found.  In short it sounds like supporting logical replication on standbys wouldn't be too hard to implement, but isn't currently planned.
