### ISSUE TITLE
How to monitor only a few tables?

### ISSUE THREAD

**Issue by abcfy2** [confluentinc/bottledwater-pg#91]
I find that bottledwater will monitor the whole database, but I just want to monitor only a few tables, how to ?

And, if a table has no PK, bottledwater will be exited. How does bottledwater will only print this waring, but will not exit? I want bottledwater to run as a background daemon.

Thanks.

**Comment by ept** [comment]
> I find that bottledwater will monitor the whole database, but I just want to monitor only a few tables, how to ?

This is not yet supported, see #21.

> And, if a table has no PK, bottledwater will be exited. How does bottledwater will only print this waring, but will not exit?

Use the `--allow-unkeyed` command line option. The error message should in fact tell you to do this.

**Comment by badboyd** [comment]
Hi @abcfy2, I have done that feature which you asking for. I can share you the code.

**Comment by samstokes** [comment]
Hi @badboyd, if you're looking for feedback on some code, please feel welcome to submit it as a Pull Request!  It doesn't need to be completely finished or perfectly polished, we should be able to help you get it there.  It might take a while for someone to respond, though, since nobody is working full-time on Bottled Water.
